# Generated by Django 3.2.9 on 2021-11-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('des', models.CharField(max_length=500)),
                ('date', models.DateField(max_length=500)),
                ('thumb', models.CharField(max_length=500)),
            ],
        ),
    ]
