# Generated by Django 3.2.9 on 2021-11-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_alter_data_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='query',
            field=models.CharField(default='NA', max_length=500),
            preserve_default=False,
        ),
    ]
